--- # local
spring:
  config:
    activate:
      on-profile: "db-local"
  jpa:
    hibernate:
트      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: test
    password: 1234
server:
  port: 8085